spring:
  application:
    name: luminary-portal

  datasource:
    url: jdbc:postgresql://localhost:5432/luminary_portal
    username: postgres
    password: r00tp@ss
  jpa:
    properties:
      hibernate:
        default_schema: jobportal
    hibernate:
      format_sql: true
      ddl-auto: update
    show-sql: true
logging:
  level:
    org.hibernate.tool.hbm2ddl: DEBUG
server:
  port: 8082

jwt:
  secret: "EweR/r/HFo8LUunsCbFbpO68EQKGAPHouKDcElM5T6M="

app:
  pagination:
    default-page: 0
    default-size: 10
